package mx.uaz.edu.SistemaBecasCASE.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.DateField;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Label;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AlumnoNuevoForm extends CssLayout {
    protected TextField tfNombre;
    protected TextField tfApPaterno;
    protected TextField tfApMaterno;
    protected DateField dfFechNac;
    protected TextField tfCurp;
    protected TextField tfEmail;
    protected TextField tfTelefono;
    protected ComboBox<mx.uaz.edu.SistemaBecasCASE.modelos.TipoAlumno> cbTipoAlumno;
    protected TextField tfCalf;
    protected TextField tfMatricula;
    protected ComboBox<mx.uaz.edu.SistemaBecasCASE.modelos.EstatusEconomico> cbEstatusEc;
    protected TextArea taComentarios;
    protected Label lblNumCarCom;
    protected TextField tfCalle;
    protected TextField tfCodigoPostal;
    protected TextField tfColonia;
    protected ComboBox<mx.uaz.edu.SistemaBecasCASE.modelos.Municipio> cbMunicipio;
    protected TextField tfNumeroExt;
    protected Button btRegistra;
    protected Button btCancelar;

    public AlumnoNuevoForm() {
        Design.read(this);
    }
}
