package mx.uaz.edu.SistemaBecasCASE.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FormComedor extends CssLayout {
    protected TextField txNombre;
    protected TextField txCalle;
    protected TextField txNumero;
    protected TextField txColonia;
    protected TextField txCodPostal;
    protected ComboBox<mx.uaz.edu.SistemaBecasCASE.modelos.Municipio> cboMunicipio;
    protected CssLayout phoneNumberWrapper;
    protected TextField txTelefono;
    protected ComboBox<String> cboDesayuno;
    protected ComboBox<String> cboComida;
    protected ComboBox<String> cboCena;
    protected Button btnAgregar;
    protected Button btnCancelar;

    public FormComedor() {
        Design.read(this);
    }
}
