package mx.uaz.edu.SistemaBecasCASE.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FormSupervisor extends CssLayout {
    protected TextField tfNombreSupervisor;
    protected TextField tfApPaterno;
    protected TextField tfApMaterno;
    protected TextField tfTelefonoCelular;
    protected TextField tfEmailSupervisor;
    protected Button btnAgregar;
    protected Button btnCancelar;

    public FormSupervisor() {
        Design.read(this);
    }
}
