package mx.uaz.edu.SistemaBecasCASE.vistas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FromResponsableDesign extends CssLayout {
    protected TextField tfNombre;
    protected TextField tfaPaterno;
    protected TextField tfaMaterno;
    protected CssLayout phoneNumberWrapper1;
    protected TextField tfTelefono;
    protected TextField tfEmail;
    protected ComboBox<mx.uaz.edu.SistemaBecasCASE.modelos.Funcion> cboFuncion;
    protected Button btnAgregarFuncion;
    protected ComboBox<mx.uaz.edu.SistemaBecasCASE.modelos.Subsede> cboSubsede;
    protected Button btnAgregarSubsede;
    protected ComboBox<mx.uaz.edu.SistemaBecasCASE.modelos.Estatus> cboEstatus;
    protected Button btnAgregar;
    protected Button btnCancelar;

    public FromResponsableDesign() {
        Design.read(this);
    }
}
